'use client';

import { ArrowDown, ArrowUp, Copy, ListChecks, Trash2, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import type { StudyOption } from '@/lib/types';

export type EditorItem = { clientId: string; id?: string; question: string; answer: string; explanation: string; options: StudyOption[] };

export function StudyItemEditor({ item, index, total, onChange, onDuplicate, onDelete, onMove }: { item: EditorItem; index: number; total: number; onChange: (item: EditorItem) => void; onDuplicate: () => void; onDelete: () => void; onMove: (direction: -1 | 1) => void }) {
  const enableOptions = () => onChange({ ...item, options: Array.from({ length: 4 }, (_, order) => ({ content: '', isCorrect: order === 0, order })) });
  const updateOption = (optionIndex: number, patch: Partial<StudyOption>) => onChange({ ...item, options: item.options.map((option, current) => current === optionIndex ? { ...option, ...patch } : patch.isCorrect ? { ...option, isCorrect: false } : option) });
  const removeOption = (optionIndex: number) => onChange({ ...item, options: item.options.filter((_, current) => current !== optionIndex).map((option, order) => ({ ...option, order })) });

  return <article className="rounded-2xl border border-border bg-card p-4 sm:p-5">
    <div className="mb-4 flex items-center justify-between gap-3"><div className="flex items-center gap-3"><span className="grid size-8 place-items-center rounded-lg bg-primary/12 text-sm font-bold text-violet-200">{index + 1}</span><span className="text-sm font-medium text-muted-foreground">Thẻ học</span></div><div className="flex items-center gap-1"><Button type="button" variant="ghost" size="icon-sm" aria-label="Di chuyển lên" disabled={index === 0} onClick={() => onMove(-1)}><ArrowUp /></Button><Button type="button" variant="ghost" size="icon-sm" aria-label="Di chuyển xuống" disabled={index === total - 1} onClick={() => onMove(1)}><ArrowDown /></Button><Button type="button" variant="ghost" size="icon-sm" aria-label="Nhân bản thẻ" onClick={onDuplicate}><Copy /></Button><Button type="button" variant="destructive" size="icon-sm" aria-label="Xóa thẻ" onClick={onDelete}><Trash2 /></Button></div></div>
    <div className="grid gap-4 lg:grid-cols-2"><label className="space-y-2"><span className="text-xs font-semibold uppercase tracking-[.08em] text-muted-foreground">Câu hỏi</span><Textarea value={item.question} onChange={(event) => onChange({ ...item, question: event.target.value })} placeholder="Nhập câu hỏi..." className="min-h-28 resize-y bg-background/30" /></label><label className="space-y-2"><span className="text-xs font-semibold uppercase tracking-[.08em] text-muted-foreground">Đáp án</span><Textarea value={item.answer} onChange={(event) => onChange({ ...item, answer: event.target.value })} placeholder="Nhập đáp án..." className="min-h-28 resize-y bg-background/30" /></label></div>
    <label className="mt-4 block space-y-2"><span className="text-xs font-semibold uppercase tracking-[.08em] text-muted-foreground">Giải thích <span className="font-normal normal-case">(không bắt buộc)</span></span><Textarea value={item.explanation} onChange={(event) => onChange({ ...item, explanation: event.target.value })} placeholder="Bổ sung mẹo nhớ hoặc giải thích..." className="min-h-20 resize-y bg-background/30" /></label>
    {item.options.length === 0 ? <Button type="button" variant="outline" className="mt-4" onClick={enableOptions}><ListChecks />Thêm đáp án trắc nghiệm</Button> : <div className="mt-5 rounded-xl border border-border bg-background/25 p-4"><div className="mb-3 flex items-center justify-between"><div><p className="text-sm font-semibold">Lựa chọn trắc nghiệm</p><p className="mt-0.5 text-xs text-muted-foreground">Chọn một đáp án đúng.</p></div><Button type="button" variant="ghost" size="sm" onClick={() => onChange({ ...item, options: [] })}><X />Bỏ trắc nghiệm</Button></div><div className="grid gap-2 sm:grid-cols-2">{item.options.map((option, optionIndex) => <div key={optionIndex} className="flex items-center gap-2 rounded-xl border border-border bg-card p-2"><input type="radio" name={`correct-${item.clientId}`} checked={option.isCorrect} onChange={() => updateOption(optionIndex, { isCorrect: true })} aria-label={`Đánh dấu lựa chọn ${optionIndex + 1} là đáp án đúng`} className="size-4 accent-violet-500" /><input value={option.content} onChange={(event) => updateOption(optionIndex, { content: event.target.value })} placeholder={`Đáp án ${String.fromCharCode(65 + optionIndex)}`} className="h-9 min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-muted-foreground" /><Button type="button" variant="ghost" size="icon-xs" aria-label={`Xóa lựa chọn ${optionIndex + 1}`} disabled={item.options.length <= 2} onClick={() => removeOption(optionIndex)}><X /></Button></div>)}</div>{item.options.length < 6 && <Button type="button" variant="ghost" size="sm" className="mt-2" onClick={() => onChange({ ...item, options: [...item.options, { content: '', isCorrect: false, order: item.options.length }] })}><span className="text-lg leading-none">+</span>Thêm lựa chọn</Button>}</div>}
  </article>;
}
